const daftarBarang = [
    { id: "buku", nama: "Buku" },
    { id: "pensil", nama: "Pensil" },
    { id: "penghapusxxxxxxxxxx", nama: "Penghapus" },
    { id: "pulpen", nama: "Pulpen" },
    { id: "buku", nama: "Buku" },
    { id: "pensil", nama: "Pensil" },
    { id: "penghapusxxxxxxxxxx", nama: "Penghapus" },
    { id: "pulpen", nama: "Pulpen" },
    { id: "buku", nama: "Buku" },
    { id: "pensil", nama: "Pensil" },
    { id: "penghapusxxxxxxxxxx", nama: "Penghapus" },
    { id: "pulpen", nama: "Pulpen" },
    { id: "buku", nama: "Buku" },
    { id: "pensil", nama: "Pensil" },
    { id: "penghapusxxxxxxxxxx", nama: "Penghapus" },
    { id: "pulpen", nama: "Pulpen" },
    { id: "buku", nama: "Buku" },
    { id: "pensil", nama: "Pensil" },
    { id: "penghapusxxxxxxxxxx", nama: "Penghapus" },
    { id: "pulpen", nama: "Pulpen" },
    { id: "buku", nama: "Buku" },
    { id: "pensil", nama: "Pensil" },
    { id: "penghapusxxxxxxxxxx", nama: "Penghapus" },
    { id: "pulpen", nama: "Pulpen" }
];
