const daftarBarang = [
    { id: "buku", nama: "Buku Tulis" },
    { id: "pensil", nama: "Pensil 2B" },
    { id: "penghapus", nama: "Penghapus Karet" },
    { id: "pulpen", nama: "Pulpen Hitam" },
    { id: "spidol", nama: "Spidol Permanen" },
    { id: "penggaris", nama: "Penggaris 30cm" },
    { id: "stabilo", nama: "Stabilo Warna" },
    { id: "gunting", nama: "Gunting Kecil" },
    { id: "lem", nama: "Lem Stick" },
    { id: "kertas", nama: "Kertas HVS A4" },
    { id: "map", nama: "Map Plastik" },
    { id: "clip", nama: "Paper Clip" },
    { id: "lakban", nama: "Lakban Bening" },
    { id: "stapler", nama: "Stapler Kecil" },
    { id: "isi_stapler", nama: "Isi Staples No.10" },
    { id: "penghitung", nama: "Penghitung Kertas" },
    { id: "folder", nama: "Folder Dokumen" },
    { id: "nota", nama: "Buku Nota" },
    { id: "id_card", nama: "ID Card Holder" },
    { id: "tinta", nama: "Tinta Printer Hitam" },
    { id: "flashdisk", nama: "Flashdisk 16GB" },
    { id: "mouse", nama: "Mouse Wireless" },
    { id: "keyboard", nama: "Keyboard USB" },
    { id: "charger", nama: "Charger HP" },
    { id: "kabel_data", nama: "Kabel Data Type-C" },
    { id: "headset", nama: "Headset Bluetooth" },
    { id: "speaker", nama: "Speaker Mini" },
    { id: "tas", nama: "Tas Ransel Laptop" },
    { id: "dompet", nama: "Dompet Kulit" },
    { id: "jam", nama: "Jam Tangan Digital" },
    { id: "payung", nama: "Payung Lipat" },
    { id: "botol", nama: "Botol Minum 1L" },
    { id: "topi", nama: "Topi Baseball" },
    { id: "masker", nama: "Masker Kain 3 Lapis" },
    { id: "kaos", nama: "Kaos Polos Hitam" },
    { id: "jaket", nama: "Jaket Hoodie" },
    { id: "celana", nama: "Celana Jeans" },
    { id: "sepatu", nama: "Sepatu Sneakers" },
    { id: "sandal", nama: "Sandal Jepit" },
    { id: "sarung_tangan", nama: "Sarung Tangan Motor" },
    { id: "helm", nama: "Helm SNI" },
    { id: "lampu", nama: "Lampu LED 5W" },
    { id: "baterai", nama: "Baterai AA" },
    { id: "obeng", nama: "Obeng Set 6 in 1" },
    { id: "tang", nama: "Tang Kombinasi" },
    { id: "martil", nama: "Martil Besi" },
    { id: "meteran", nama: "Meteran 5m" },
    { id: "bor", nama: "Bor Listrik" }
];
